version: "3.9"

services:

  ingestor:
    container_name: radar-ingestor
    build: ./ingestor-service
    ports:
      - "8081:8080"
    depends_on:
      - prometheus

  analyzer:
    container_name: radar-analyzer
    build: ./analyzer-service
    ports:
      - "8082:8080"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    depends_on:
      - prometheus
      - alertmanager   # <-- nos aseguramos de que Alertmanager estÃ© arriba

  prometheus:
    container_name: radar-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml   # <-- montamos reglas
    ports:
      - "9090:9090"

  alertmanager:
    container_name: radar-alertmanager
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=info
    ports:
      - "9093:9093"

  dashboard:
    container_name: radar-dashboard
    image: nginx:latest
    volumes:
      - ./dashboard:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - analyzer

  grafana:
    container_name: radar-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
  