global:
  # Cada cuÃ¡nto se hace scrape a los targets
  scrape_interval: 15s

# ğŸ”” Archivos de reglas de alerta
rule_files:
  - "/etc/prometheus/alerts.yml"   #  <-- Debe coincidir con ruta docker

scrape_configs:
  # (Opcional pero recomendado) Prometheus se scrapea a sÃ­ mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Nuestro ingestor de mÃ©tricas Spring Boot
  - job_name: "ingestor"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ingestor:8080"]
