global:
  scrape_interval: 15s  # frecuencia de scrapes

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Reglas de alerta que serán cargadas
rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:

  # Prometheus se monitorea a sí mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Servicio ingestor (Spring Boot con Micrometer)
  - job_name: "ingestor"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["100.30.148.203:8081"]
